AllCops:
  TargetRubyVersion: 2.7.6
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 35
  IgnoredMethods: ['describe']

Naming/PredicateName:
  Description: 'Check the names of predicate methods.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#bool-methods-qmark'
  ForbiddenPrefixes:
    - is_
  Exclude:
    - spec/**/*
